In [2]:
import pandas as pd

In [3]:
datos=pd.DataFrame({'id':['id0','id1','id2','id3','id4'],
              'nombre':['Joaquin','Sol','Alejandro','Bautista','Aldana'],
              'edad':[31, 35, 30, 25, 28],
              'altura_m':[1.81, 1.75, 1.60, 1.85, 1.70],
              'ciudad':['Rosario','Rosario','CABA','Victoria','Santa Fe']})

In [4]:
datos

    id     nombre  edad  altura_m    ciudad
0  id0    Joaquin    31      1.81   Rosario
1  id1        Sol    35      1.75   Rosario
2  id2  Alejandro    30      1.60      CABA
3  id3   Bautista    25      1.85  Victoria
4  id4     Aldana    28      1.70  Santa Fe

In [5]:
datos[datos['ciudad']=='Rosario']

    id   nombre  edad  altura_m   ciudad
0  id0  Joaquin    31      1.81  Rosario
1  id1      Sol    35      1.75  Rosario

In [6]:
datos.loc[datos['ciudad']=='Rosario']

    id   nombre  edad  altura_m   ciudad
0  id0  Joaquin    31      1.81  Rosario
1  id1      Sol    35      1.75  Rosario

In [7]:
datos.set_index('id',inplace=True)

In [8]:
datos.iloc[2]

nombre      Alejandro
edad               30
altura_m          1.6
ciudad           CABA
Name: id2, dtype: object

## PERSONAS

In [9]:
personas=pd.read_csv('lista_personas.csv')

In [10]:
personas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Apellido          16 non-null     object
 1   Nombre            16 non-null     object
 2   DNI               16 non-null     object
 3   Fecha_nacimiento  16 non-null     object
dtypes: object(4)
memory usage: 644.0+ bytes

In [11]:
personas

     Apellido     Nombre        DNI Fecha_nacimiento
0       Pedro   González  41 523661         8/4/1998
1     Joaquín  Fernández   34567895         6/6/1990
2      Silvia     Nuncia   14697454       15/12/1961
3     Luciano       Lima   28475692         2/7/1980
4        Lara      Pérez   35647892         9/4/1991
5        José       Vera   36457896        9/10/1992
6       Sofía       Moro   37412569        14/4/1994
7      Silvia     Torres   37445307         4/7/1994
8   Sebastián     García   34567910         2/1/1990
9        Juan     Guerra   36459591        15/9/1992
10    Ignacio      Rocha   37414652        30/4/1994
11    Lusiano      Vilas   34572461        2/11/1989
12      Paola    Benítez   40256784        25/2/1997
13      Brisa       Moro   41236584        16/7/1998
14    Liliana      Gómez   14256845        5/12/1961
15     Silvia  Fernández   43856741        24/3/2001

In [12]:
personas.rename(columns={'Apellido':'Nombre',
                         'Nombre':'Apellido'})

       Nombre   Apellido        DNI Fecha_nacimiento
0       Pedro   González  41 523661         8/4/1998
1     Joaquín  Fernández   34567895         6/6/1990
2      Silvia     Nuncia   14697454       15/12/1961
3     Luciano       Lima   28475692         2/7/1980
4        Lara      Pérez   35647892         9/4/1991
5        José       Vera   36457896        9/10/1992
6       Sofía       Moro   37412569        14/4/1994
7      Silvia     Torres   37445307         4/7/1994
8   Sebastián     García   34567910         2/1/1990
9        Juan     Guerra   36459591        15/9/1992
10    Ignacio      Rocha   37414652        30/4/1994
11    Lusiano      Vilas   34572461        2/11/1989
12      Paola    Benítez   40256784        25/2/1997
13      Brisa       Moro   41236584        16/7/1998
14    Liliana      Gómez   14256845        5/12/1961
15     Silvia  Fernández   43856741        24/3/2001