### **Ejercicio N°5**

Usando los datos de `listings_ba.csv` de Buenos Aires que se encuentran cargados en el campus realice la imputación de los precios de alquiler faltantes empleando:

1. La media y moda de los datos no faltantes 

2. Una medida de resumen de su elección por barrio y tipo de habitación

3. Los 10 puntos más cercanos geográficamente a cada dato faltante usando las coordenadas.

En cada uno de los casos indicar la cantidad de datos que se usaron para la imputación.

In [3]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np

In [4]:
alquileres=pd.read_csv('./datasets/listings_ba.csv')
alquileres

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,11508,Amazing Luxurious Apt-Palermo Soho,42762,Candela,NaN,Palermo,-34.581840,-58.424150,Entire home/apt,21143.0,3,33,2022-12-19,0.26,1,309,6,NaN
1,14222,"RELAX IN HAPPY HOUSE - PALERMO, BUENOS AIRES",87710233,María,NaN,Palermo,-34.586170,-58.410360,Entire home/apt,5728.0,7,102,2022-12-05,0.80,4,305,11,NaN
2,317484,Single Room in Palermo Soho,1621752,Luba,NaN,Palermo,-34.589920,-58.422360,Private room,3348.0,2,160,2022-12-10,1.22,4,349,5,NaN
3,15074,ROOM WITH RIVER SIGHT,59338,Monica,NaN,Nuñez,-34.538920,-58.465990,Private room,5286.0,29,0,NaN,NaN,1,365,0,NaN
4,118070,Amazing view - GREAT Studio - Balcony,530261,Luciano,NaN,Palermo,-34.583110,-58.427670,Entire home/apt,10572.0,14,49,2022-07-22,0.36,27,349,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20080,789876010794026163,Mono ambiente vista panorámica,161559109,Juan,NaN,Caballito,-34.608729,-58.460363,Entire home/apt,6080.0,1,0,NaN,NaN,18,331,0,NaN
20081,791445322793116711,Departamento recoleta amplio.,154496179,Ramiro,NaN,Recoleta,-34.590495,-58.400738,Entire home/apt,7048.0,3,0,NaN,NaN,1,364,0,NaN
20082,789883094728711215,Palermo Ápt bohemia,60115955,Hache,NaN,Palermo,-34.584193,-58.440578,Entire home/apt,2114.0,4,0,NaN,NaN,15,342,0,NaN
20083,789886886364996844,Departamento en Congreso de Buenos Aires + coch,119161621,Camila,NaN,Monserrat,-34.610114,-58.390820,Entire home/apt,10500.0,2,0,NaN,NaN,1,339,0,NaN
20084,789889818985355570,Dulce hogar Belgrano R,48005753,Federico,NaN,Belgrano,-34.561013,-58.463017,Entire home/apt,9867.0,2,0,NaN,NaN,2,90,0,NaN

In [5]:
alquileres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20085 entries, 0 to 20084
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20085 non-null  int64
 1   name                            20082 non-null  object
 2   host_id                         20085 non-null  int64
 3   host_name                       20085 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   20085 non-null  object
 6   latitude                        20085 non-null  float64
 7   longitude                       20085 non-null  float64
 8   room_type                       20085 non-null  object
 9   price                           19985 non-null  float64
 10  minimum_nights                  20085 non-null  int64
 11  number_of_reviews               20085 non-null  int64
 12  last_review                     16254 non-null  object
 13  reviews_per_month               16254 non-null  float64
 14  calculated_host_listings_count  20085 non-null  int64
 15  availability_365                20085 non-null  int64
 16  number_of_reviews_ltm           20085 non-null  int64
 17  license                         413 non-null    object
dtypes: float64(5), int64(7), object(6)
memory usage: 2.8+ MB

In [15]:
#precio media y moda de todos
df_a=alquileres.copy()
precio_media=df_a['price'].mean()
precio_moda=df_a['price'].mode()[0]
print(f'Media= ${round(precio_media,2)} y moda= ${round(precio_moda,2)}')

Media= $16479.11 y moda= $8810.0

In [45]:
df_a['price']=df_a['price'].fillna(precio_media)
df_a

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,11508,Amazing Luxurious Apt-Palermo Soho,42762,Candela,NaN,Palermo,-34.581840,-58.424150,Entire home/apt,21143.0,3,33,2022-12-19,0.26,1,309,6,NaN
1,14222,"RELAX IN HAPPY HOUSE - PALERMO, BUENOS AIRES",87710233,María,NaN,Palermo,-34.586170,-58.410360,Entire home/apt,5728.0,7,102,2022-12-05,0.80,4,305,11,NaN
2,317484,Single Room in Palermo Soho,1621752,Luba,NaN,Palermo,-34.589920,-58.422360,Private room,3348.0,2,160,2022-12-10,1.22,4,349,5,NaN
3,15074,ROOM WITH RIVER SIGHT,59338,Monica,NaN,Nuñez,-34.538920,-58.465990,Private room,5286.0,29,0,NaN,NaN,1,365,0,NaN
4,118070,Amazing view - GREAT Studio - Balcony,530261,Luciano,NaN,Palermo,-34.583110,-58.427670,Entire home/apt,10572.0,14,49,2022-07-22,0.36,27,349,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20080,789876010794026163,Mono ambiente vista panorámica,161559109,Juan,NaN,Caballito,-34.608729,-58.460363,Entire home/apt,6080.0,1,0,NaN,NaN,18,331,0,NaN
20081,791445322793116711,Departamento recoleta amplio.,154496179,Ramiro,NaN,Recoleta,-34.590495,-58.400738,Entire home/apt,7048.0,3,0,NaN,NaN,1,364,0,NaN
20082,789883094728711215,Palermo Ápt bohemia,60115955,Hache,NaN,Palermo,-34.584193,-58.440578,Entire home/apt,2114.0,4,0,NaN,NaN,15,342,0,NaN
20083,789886886364996844,Departamento en Congreso de Buenos Aires + coch,119161621,Camila,NaN,Monserrat,-34.610114,-58.390820,Entire home/apt,10500.0,2,0,NaN,NaN,1,339,0,NaN
20084,789889818985355570,Dulce hogar Belgrano R,48005753,Federico,NaN,Belgrano,-34.561013,-58.463017,Entire home/apt,9867.0,2,0,NaN,NaN,2,90,0,NaN

In [ ]:
#medida resumen por barrio y tipo de habitacion
# uso transform para obtener la misma cantidad de rows, sino obtengo muchas menos
df_b=alquileres.copy()
#round(df_b.groupby(['neighbourhood','room_type'])['price'].mean(),2)
precio_media_barrio_room=round(df_b.groupby(['neighbourhood', 'room_type'])['price'].transform('mean'),2)

0        19182.28
1        19182.28
2        10254.23
3        29953.12
4        19182.28
           ...
20080    10580.90
20081    14243.82
20082    19182.28
20083    18723.26
20084    13164.54
Name: price, Length: 20085, dtype: float64

In [51]:
df_b['price']=df_b['price'].fillna(precio_media_barrio_room)
df_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20085 entries, 0 to 20084
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20085 non-null  int64
 1   name                            20082 non-null  object
 2   host_id                         20085 non-null  int64
 3   host_name                       20085 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   20085 non-null  object
 6   latitude                        20085 non-null  float64
 7   longitude                       20085 non-null  float64
 8   room_type                       20085 non-null  object
 9   price                           20085 non-null  float64
 10  minimum_nights                  20085 non-null  int64
 11  number_of_reviews               20085 non-null  int64
 12  last_review                     16254 non-null  object
 13  reviews_per_month               16254 non-null  float64
 14  calculated_host_listings_count  20085 non-null  int64
 15  availability_365                20085 non-null  int64
 16  number_of_reviews_ltm           20085 non-null  int64
 17  license                         413 non-null    object
dtypes: float64(5), int64(7), object(6)
memory usage: 2.8+ MB

In [31]:
df_b[['id','name','neighbourhood','room_type','price']]

,id,name,neighbourhood,room_type,price
0,11508,Amazing Luxurious Apt-Palermo Soho,Palermo,Entire home/apt,21143.0
1,14222,"RELAX IN HAPPY HOUSE - PALERMO, BUENOS AIRES",Palermo,Entire home/apt,5728.0
2,317484,Single Room in Palermo Soho,Palermo,Private room,3348.0
3,15074,ROOM WITH RIVER SIGHT,Nuñez,Private room,5286.0
4,118070,Amazing view - GREAT Studio - Balcony,Palermo,Entire home/apt,10572.0
...,...,...,...,...,...
20080,789876010794026163,Mono ambiente vista panorámica,Caballito,Entire home/apt,6080.0
20081,791445322793116711,Departamento recoleta amplio.,Recoleta,Entire home/apt,7048.0
20082,789883094728711215,Palermo Ápt bohemia,Palermo,Entire home/apt,2114.0
20083,789886886364996844,Departamento en Congreso de Buenos Aires + coch,Monserrat,Entire home/apt,10500.0
20084,789889818985355570,Dulce hogar Belgrano R,Belgrano,Entire home/apt,9867.0

In [46]:
# alquileres con precio NA
dfNA=alquileres[alquileres['price'].isna()]
dfNA

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
67,53097,Duplex-Loft in Historic Quartier of Buenos Aires,64880,Elbio Mariano,NaN,Monserrat,-34.614940,-58.375170,Entire home/apt,NaN,2,37,2022-07-05,0.25,9,347,1,NaN
418,982269,The Best Place To Live BuenosAires!,370901,Rocio & Nicolas,NaN,Palermo,-34.581960,-58.406860,Entire home/apt,NaN,2,463,2022-11-13,3.88,1,334,24,NaN
656,1843093,Loft in Palermo Hollywood.Pool. 413,119613,Marcos,NaN,Palermo,-34.575980,-58.435370,Entire home/apt,NaN,10,42,2022-12-10,0.39,8,22,8,NaN
867,2070080,Cozy One Bedroom in Palermo,288132,Noel,NaN,Palermo,-34.583340,-58.414960,Entire home/apt,NaN,3,82,2022-12-22,0.75,1,222,18,NaN
983,2380405,"Room, private toilette at Cañitas",12002481,Ines,NaN,Palermo,-34.571070,-58.429250,Private room,NaN,10,3,2018-03-03,0.03,2,331,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18322,756247760985068567,"Palermo area, modern studio, digital nomads he...",524235,Marcelo,NaN,Almagro,-34.599640,-58.425370,Entire home/apt,NaN,2,3,2022-11-15,1.80,1,317,3,NaN
18341,756327088733090624,Hermoso departamento en excelente ubicación,487005972,Natalia,NaN,Parque Chacabuco,-34.633260,-58.446410,Entire home/apt,NaN,2,3,2022-11-25,1.91,1,319,3,NaN
19049,770489317518013872,Excelente depto en BA,141109923,Alejandro,NaN,San Nicolas,-34.608139,-58.380583,Entire home/apt,NaN,2,2,2022-12-20,2.00,1,77,2,NaN
19633,782212364526055405,Elegante departamento en Palermo,487454828,Miguel Angel Fabrizio,NaN,Palermo,-34.569160,-58.441410,Entire home/apt,NaN,1,1,2022-12-23,1.00,4,363,1,NaN
19955,786976326601163171,Araoz house en palermo soho,346169874,Lucas,NaN,Palermo,-34.590570,-58.422643,Entire home/apt,NaN,4,0,NaN,NaN,21,360,0,NaN

In [43]:
lista_ids = dfNA['id'].tolist()

In [49]:
#NA llenos en df_a
resultadoA=df_a[df_a['id'].isin(lista_ids)]
resultadoA[['id','name','neighbourhood','room_type','price']]

,id,name,neighbourhood,room_type,price
67,53097,Duplex-Loft in Historic Quartier of Buenos Aires,Monserrat,Entire home/apt,16479.10633
418,982269,The Best Place To Live BuenosAires!,Palermo,Entire home/apt,16479.10633
656,1843093,Loft in Palermo Hollywood.Pool. 413,Palermo,Entire home/apt,16479.10633
867,2070080,Cozy One Bedroom in Palermo,Palermo,Entire home/apt,16479.10633
983,2380405,"Room, private toilette at Cañitas",Palermo,Private room,16479.10633
...,...,...,...,...,...
18322,756247760985068567,"Palermo area, modern studio, digital nomads he...",Almagro,Entire home/apt,16479.10633
18341,756327088733090624,Hermoso departamento en excelente ubicación,Parque Chacabuco,Entire home/apt,16479.10633
19049,770489317518013872,Excelente depto en BA,San Nicolas,Entire home/apt,16479.10633
19633,782212364526055405,Elegante departamento en Palermo,Palermo,Entire home/apt,16479.10633
19955,786976326601163171,Araoz house en palermo soho,Palermo,Entire home/apt,16479.10633

In [52]:
#NA llenos en df_b
resultadoB=df_b[df_b['id'].isin(lista_ids)]
resultadoB[['id','name','neighbourhood','room_type','price']]

,id,name,neighbourhood,room_type,price
67,53097,Duplex-Loft in Historic Quartier of Buenos Aires,Monserrat,Entire home/apt,18723.26
418,982269,The Best Place To Live BuenosAires!,Palermo,Entire home/apt,19182.28
656,1843093,Loft in Palermo Hollywood.Pool. 413,Palermo,Entire home/apt,19182.28
867,2070080,Cozy One Bedroom in Palermo,Palermo,Entire home/apt,19182.28
983,2380405,"Room, private toilette at Cañitas",Palermo,Private room,10254.23
...,...,...,...,...,...
18322,756247760985068567,"Palermo area, modern studio, digital nomads he...",Almagro,Entire home/apt,26736.85
18341,756327088733090624,Hermoso departamento en excelente ubicación,Parque Chacabuco,Entire home/apt,6923.10
19049,770489317518013872,Excelente depto en BA,San Nicolas,Entire home/apt,9308.69
19633,782212364526055405,Elegante departamento en Palermo,Palermo,Entire home/apt,19182.28
19955,786976326601163171,Araoz house en palermo soho,Palermo,Entire home/apt,19182.28