In [1]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np

### **Ejercicio N°4**

La siguiente tabla resume la evolución de la población total argentina desde 1960 a la actualidad según los censos nacionales de población (fuente: [INDEC](https://www.indec.gob.ar/indec/web/Nivel4-Tema-2-18-77#:~:text=Aqu%C3%AD%20presentamos%20los%20datos%20del,de%20la%20poblaci%C3%B3n%20del%20pa%C3%ADs.&text=La%20poblaci%C3%B3n%20nacional%20est%C3%A1%20compuesta,mujeres%20hay%2094%2C8%20varones.)):

| **Año** | **Población total** |
| --- | --- |
| 1960 | 20013793 |
| 1970 | 23364431 |
| 1978 |  |
| 1980 | 27949780 |
| 1986 |  |
| 1991 | 32615528 |
| 2001 | 36260130 |
| 2010 | 40117096 |
| 2014 |  |
| 2022 | 46044703 |

Utilizando una interpolación lineal, complete la información sobre **Población total** para aquellos años en los que no se cuenta con datos de censos nacionales.

In [3]:
censos=pd.DataFrame({
    'Año':[1960, 1970, 1978, 1980, 1986, 1991, 2001, 2010, 2014, 2022],
    'Poblacion':[20013793, 23364431, np.nan, 27949780, np.nan, 32615528, 36260130, 40117096, np.nan, 46044703]})
censos

    Año   Poblacion
0  1960  20013793.0
1  1970  23364431.0
2  1978         NaN
3  1980  27949780.0
4  1986         NaN
5  1991  32615528.0
6  2001  36260130.0
7  2010  40117096.0
8  2014         NaN
9  2022  46044703.0

In [10]:
censos['Poblacion']=censos['Poblacion'].interpolate(method='values')
censos

    Año   Poblacion
0  1960  20013793.0
1  1970  23364431.0
2  1978  25657105.5
3  1980  27949780.0
4  1986  30282654.0
5  1991  32615528.0
6  2001  36260130.0
7  2010  40117096.0
8  2014  43080899.5
9  2022  46044703.0

In [12]:
censos[censos['Año'].isin([1978, 1986, 2014])]

    Año   Poblacion
2  1978  25657105.5
4  1986  30282654.0
8  2014  43080899.5

In [ ]:
censos_sin_NA=censos.dropna()

In [9]:
#con numpy
interpolacion2=np.interp([1978,1986,2014],censos_sin_NA['Año'],censos_sin_NA['Poblacion'])
interpolacion2

array([27032710.2       , 30494733.45454545, 42092965.        ])