In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('./datasets/flete-aereo-vacunas-covid19-al-2021-06-28.xlsx') #header=4 para saltar las primeras filas. yo las borre porque hice trampa

In [3]:
df.head()

,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
0,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
1,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 302.250,00",044-44032940,"USD 304.570,16",2020-12-23,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
2,Ministerio de Salud de la Nación,EX-2021-04601170- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24666588-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011206,"USD 302.250,00",044-44032973,"USD 302.250,00",2021-01-15,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
3,Ministerio de Salud de la Nación,EX-2021-08460702- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24639513-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011296,NaN,044-44032984,"USD 268.655,94",2021-01-29,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
4,Ministerio de Salud de la Nación,EX-2021-13211127- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24642675-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011370,"USD 303.075,00",044-44032995,"USD 303.075,00",2021-02-11,1065,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048571 entries, 0 to 1048570
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   organismo                       66 non-null     object
 1   expediente                      66 non-null     object
 2   financiamiento                  67 non-null     object
 3   acto_conclusión                 66 non-null     object
 4   descripción                     66 non-null     object
 5   prestador                       66 non-null     object
 6   CUIT                            66 non-null     object
 7   estado                          66 non-null     object
 8   factura_nro                     66 non-null     object
 9   factura_moneda_monto            64 non-null     object
 10  guía_nro                        66 non-null     object
 11  guía_moneda_monto               64 non-null     object
 12  fecha_guía                      66 non-null     datetime64[ns]
 13  vuelo                           63 non-null     object
 14  bienes_transportados            66 non-null     object
 15  proveedor_bienes_transportados  66 non-null     object
 16  operación                       66 non-null     object
 17  comprador_donante               66 non-null     object
 18  origen                          66 non-null     object
dtypes: datetime64[ns](1), object(18)
memory usage: 152.0+ MB

* Según la información que se encuentra en la base de datos, ¿cuál fue el número de vuelo que realizó una mayor cantidad de fletes? Sugerencia: utilice el método value_counts() de la librería Pandas.

In [24]:
df['vuelo '].value_counts()

vuelo
1061                   15
1063                   12
1065                    9
1051                    7
1081                    6
1067                    4
1069                    3
1501                    2
QR8351/16-QR8155/16     1
KL701                   1
KL892                   1
LH8433                  1
LH8434                  1
Name: count, dtype: int64

In [25]:
df.groupby('vuelo ').size().sort_values(ascending=False)#.head(1)

vuelo
1061                   15
1063                   12
1065                    9
1051                    7
1081                    6
1067                    4
1069                    3
1501                    2
KL701                   1
KL892                   1
LH8433                  1
LH8434                  1
QR8351/16-QR8155/16     1
dtype: int64

In [30]:
df['vuelo '].isnull()

0          False
1          False
2          False
3          False
4          False
           ...
1048566     True
1048567     True
1048568     True
1048569     True
1048570     True
Name: vuelo , Length: 1048571, dtype: bool

In [32]:
df=df.dropna(axis=0, thresh=3) #axis=0 dropea filas #tresh se usa para dropear la fila segun la cantidad de nulls que haya, me dijo que ponga 3

* ¿Cuántos registros no contienen información sobre el número de vuelo?

In [38]:
df['vuelo '].isnull().sum()

np.int64(3)

* Calcule el promedio de lo facturado en todos los vuelos realizados considerando únicamente los registros de viajes que se facturaron en USD según la información contenida en la columna factura_moneda_monto.

In [39]:
df.head()

,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
0,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
1,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 302.250,00",044-44032940,"USD 304.570,16",2020-12-23,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
2,Ministerio de Salud de la Nación,EX-2021-04601170- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24666588-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011206,"USD 302.250,00",044-44032973,"USD 302.250,00",2021-01-15,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
3,Ministerio de Salud de la Nación,EX-2021-08460702- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24639513-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011296,NaN,044-44032984,"USD 268.655,94",2021-01-29,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
4,Ministerio de Salud de la Nación,EX-2021-13211127- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24642675-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011370,"USD 303.075,00",044-44032995,"USD 303.075,00",2021-02-11,1065,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia

In [40]:
df['factura_moneda_monto'].value_counts()

factura_moneda_monto
USD 428.000,00     5
USD 302.250,00     2
USD 12.039,50      2
USD 304.650,00     2
USD 428.000        2
USD 131.143,00     2
USD 303.075,00     1
EUR 158.117,70     1
EUR 237.859,45     1
USD 133.783,00     1
USD 301.025,00     1
USD 105.084,89     1
EUR 72.134,00      1
USD 297.800,00     1
EUR 241.789,00     1
USD 298.550,00     1
USD 294.750,00     1
EUR 77.546,14      1
USD 8.909,23       1
EUR 129.737,00     1
USD 28.754,34      1
USD 301.850,00     1
USD 305.250,00     1
EUR 156.047,78     1
USD 31.709,00      1
USD 7.273,18       1
USD 11.985,20      1
EUR 333.549,02     1
USD 19.263,20      1
USD 293.475,00     1
USD 292.875,00     1
USD 88.436,12      1
USD  132.709,00    1
EUR 159.625,86     1
USD 303.950,00     1
USD 12.039, 50     1
EUR 120.943,65     1
USD 300.500,00     1
USD 300.900,00     1
USD 124.122,00     1
USD 301.900,00     1
USD 2.850,00       1
USD 304.400,00     1
EUR 334.515,76     1
USD 14.687,34      1
EUR 90.404,78      1
EUR -7.760,00      1
EUR -260,00        1
USD 9.391,54       1
USD 1.926,32       1
EUR 39.000,80      1
USD 303.050,00     1
EUR 331.069,72     1
USD 19.700,23      1
USD 259.052,99     1
Name: count, dtype: int64

In [43]:
patron = r'^USD\s[0-9.,]+'
filtro_usd = df['factura_moneda_monto'].str.contains(patron, regex=True, na=False)

In [ ]:
columna_aislada = df.loc[filtro_usd, 'factura_moneda_monto'].copy()

0      True
1      True
2      True
3     False
4      True
      ...
61    False
62     True
63     True
64     True
65     True
Name: factura_moneda_monto, Length: 66, dtype: bool